### Registro de usuario admin
POST http://localhost:8080/api/auth/registro
Content-Type: application/json

{
  "nombre": "Admin Test",
  "email": "admin@test.com",
  "password": "123456",
  "dni": 12345678,
  "rol": "ADMINISTRADOR"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "dni": 12345678,
  "password": "123456"
}

### Reclamos sin filtro
GET http://localhost:8080/api/reclamos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4


### Filtro por estado
GET http://localhost:8080/api/reclamos?estado=PENDIENTE
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

### Filtro por estado inválido (debería dar 400)
GET http://localhost:8080/api/reclamos?estado=INVALIDO
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

### Ver luminarias
GET http://localhost:8080/api/luminarias
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

### Ver tipos de reclamo
GET http://localhost:8080/api/tc
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

#####################
### Crear reclamo 1
POST http://localhost:8080/api/reclamos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4
Content-Type: application/json

{
  "tipoReclamoId": 1,
  "usuarioId": 1
}

### Crear reclamo 2
POST http://localhost:8080/api/reclamos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4
Content-Type: application/json

{
  "tipoReclamoId": 4,
  "usuarioId": 1
}


### Todos los reclamos
GET http://localhost:8080/api/reclamos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

### Solo por tipo de reclamo 1 (Luminaria apagada)
GET http://localhost:8080/api/reclamos?tipoReclamoId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

### Solo por tipo de reclamo 4 (Corte de luz general)
GET http://localhost:8080/api/reclamos?tipoReclamoId=4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4


### Crear luminaria 1
POST http://localhost:8080/api/luminarias
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4
Content-Type: application/json

{
  "tipo": "LED",
  "estado": "Funciona",
  "potencia": "150W",
  "zonaId": 1,
  "latitud": -38.1667,
  "longitud": -58.9667
}

### Crear luminaria 2
POST http://localhost:8080/api/luminarias
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4
Content-Type: application/json

{
  "tipo": "Sodio",
  "estado": "Rota",
  "potencia": "100W",
  "zonaId": 2,
  "latitud": -38.1700,
  "longitud": -58.9700
}


### Todas
GET http://localhost:8080/api/luminarias
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

### Solo las que funcionan
GET http://localhost:8080/api/luminarias?estado=Funciona
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4
### Solo zona 2
GET http://localhost:8080/api/luminarias?zonaId=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4MzAzOTk5LCJleHAiOjE3ODgzOTAzOTl9.gbtM9zyyUd-TtU9mb16NnwMUq3rZhDbY-Iq8OgwAee4

###
GET http://localhost:8080/api/zonas
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4NDc1Mzg4LCJleHAiOjE3ODg1NjE3ODh9.8yTEByvBAjaMHVoDcVgxtB3VWQLRK8Qw_ig91HD9Ujk

### Verificar que el backend anda
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "dni": 12345678,
  "password": "123456"
}


### Crear reclamo
POST http://localhost:8080/api/reclamos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4NDc1Mzg4LCJleHAiOjE3ODg1NjE3ODh9.8yTEByvBAjaMHVoDcVgxtB3VWQLRK8Qw_ig91HD9Ujk
Content-Type: application/json

{
  "tipoReclamoId": 1,
  "usuarioId": 1
}


### Transición válida: PENDIENTE → ASIGNADO
PATCH http://localhost:8080/api/reclamos/5/estado
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4NDc1Mzg4LCJleHAiOjE3ODg1NjE3ODh9.8yTEByvBAjaMHVoDcVgxtB3VWQLRK8Qw_ig91HD9Ujk
Content-Type: application/json

{
  "estado": "ASIGNADO",
  "observacion": "Asignado a cuadrilla zona norte"
}

### Transición válida: PENDIENTE → ASIGNADO
PATCH http://localhost:8080/api/reclamos/5/estado?estado=ASIGNADO&observacion=Asignado a cuadrilla zona norte
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4NDc1Mzg4LCJleHAiOjE3ODg1NjE3ODh9.8yTEByvBAjaMHVoDcVgxtB3VWQLRK8Qw_ig91HD9Ujk


### Transición inválida: ASIGNADO → CERRADO (no debería permitirlo)
PATCH http://localhost:8080/api/reclamos/5/estado?estado=CERRADO&observacion=Intentando cerrar
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4NDc1Mzg4LCJleHAiOjE3ODg1NjE3ODh9.8yTEByvBAjaMHVoDcVgxtB3VWQLRK8Qw_ig91HD9Ujk



### Ver cuadrillas
GET http://localhost:8080/api/cuadrillas
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4OTA0Nzg1LCJleHAiOjE3ODg5OTExODV9.ODoosevqi4v2dVQ428RktE2SQccA0d8oD84BxmRSmMY

### Crear cuadrilla
POST http://localhost:8080/api/cuadrillas
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4OTA0Nzg1LCJleHAiOjE3ODg5OTExODV9.ODoosevqi4v2dVQ428RktE2SQccA0d8oD84BxmRSmMY
Content-Type: application/json

{
  "nombre": "Cuadrilla Norte"
}

### Asignar admin a cuadrilla (debería fallar)
POST http://localhost:8080/api/cuadrilla-tecnicos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJub21icmUiOiJBZG1pbiBUZXN0IiwiaWF0IjoxNzg4OTA0Nzg1LCJleHAiOjE3ODg5OTExODV9.ODoosevqi4v2dVQ428RktE2SQccA0d8oD84BxmRSmMY
Content-Type: application/json

{
  "cuadrillaId": 1,
  "tecnicoId": 1
}


