spring.application.name=backend-alumbrado

# Configuraci�n de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/alumbrado_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Spring Boot 3 + PostGIS)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway para migraciones autom�ticas de BD
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Configuraci�n JWT (Clave con m�nimo 32 caracteres)
jwt.secret=ClaveJWTAlumbradoPublicoLoberiaPieres2025!
jwt.expiration=86400000